use std::error::Error;
mod task_01;

fn main() -> Result<(), Box<dyn Error>> {
    task_01::main()
}
